### ISSUE TITLE
putExistingCustomerCallsSave_Test doesn't match README instructions

### ISSUE THREAD

**Issue by DanielWinks** [jeff-anderson-cscc/java4-labs-rest-controllers#1]
The test for `putExistingCustomerCallsSave_Test` includes `.andExpect(status().isNoContent())`, which doesn't seem to align with the README.md section for this: "Step 1.1.4 creates a response entity with the return data and HttpStatus.OK if step 1.1.1 returns true"

It seems this should probably be `status().isOk()` instead?

**Comment by DanielWinks** [comment]
Also, the README.md states under the [first section](https://github.com/jeff-anderson-cscc/java4-labs-rest-controllers#completing-the-assignment): "Open CustomerControllerValidationTests" when this probably should be "CustomerControllerTests".

**Comment by jeff-anderson-cscc** [comment]
Check it out and see if I missed anything. Thanks for the feedback!

**Comment by DanielWinks** [comment]
That's all I noticed. Thanks.
